version: 2

defaults: &defaults
  machine:
    docker_layer_caching: true
  environment:
    - APP_VERSION: $CIRCLE_SHA1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: docker build -t ${IMAGE_NAME} .
      - run: docker run -d --rm --name node_app ${IMAGE_NAME}
      - run: docker stop node_app

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: docker build --rm=false --build-arg APP_VERSION=$CIRCLE_SHA1 -t eu.gcr.io/${GCP_PEOJECT}/${IMAGE_NAME}:$CIRCLE_SHA1
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1


  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run: echo $ID_RSA | base64 -d > id_rsa && chmod 400 id_rsa
  #     - run: ssh -i id_rsa core@$VM_IP "IMAGE=${IMAGE_NAME}:$CIRCLE_SHA1 bash -s" < deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test:
          context: nodeapp
      - publish:
          requires:
            - test
          context: nodeapp
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - publish
      #     context: nodeapp