version: 2

defaults: &defaults
  machine:
    docker_layer_caching: true
  environment:
    - APP_VERSION: $CIRCLE_SHA1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: docker build -t ${image_name} .
      - run: docker run -d --rm --name node_app ${image_name}
      - run: docker stop node_app

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      # - run: echo ${MONGO_URI} > ${HOME}/MONGO_URI
      - run: docker build --build-arg buildtime_variable=$MONGO_URI --rm=false -t eu.gcr.io/${gcp_project}/${image_name} .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${gcp_project}
      - run: gcloud docker -- push eu.gcr.io/${gcp_project}/${image_name}


  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run: echo $ID_RSA | base64 -d > id_rsa && chmod 400 id_rsa
  #     - run: ssh -i id_rsa core@$VM_IP "IMAGE=${image_name}:$CIRCLE_SHA1 bash -s" < deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test:
          context: nodeapp
      - publish:
          requires:
            - test
          context: nodeapp
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - publish
      #     context: nodeapp